# Generated by Django 5.2.8 on 2025-11-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gift_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='price',
        ),
        migrations.AddField(
            model_name='gift',
            name='item_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_url', models.CharField(default='', max_length=500)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipient')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='wish_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.wishlist'),
        ),
    ]
