# Generated by Django 5.2.8 on 2025-11-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gift_price_gift_item_url_wishlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='item_url',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_url',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
