# Generated by Django 5.2.8 on 2025-11-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_gift_item_url_alter_wishlist_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='app.recipient'),
        ),
    ]
