# Generated by Django 5.2.8 on 2025-11-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_wishlist_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='product_image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='product_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
